version: '3.2'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9000"
    volumes:
      - ../app:/data/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    restart: always
    command: php-fpm
    hostname: "php-fpm"
    working_dir: /app
    links:
      - kafka
      - xunsearch
    depends_on:
      - kafka
  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../app:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
      - "80"
      - "443"
    restart: always
    command: nginx -g 'daemon off;'
  #<!--定义zk层服务-->
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181"
  #<!--定义Kafka层-->
  kafka:
    image: wurstmeister/kafka
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  xunsearch:
    hostname: "xunsearch"
    image: hightman/xunsearch
    container_name: xunsearch
    volumes:
      - ./data/xunsearch:/usr/local/xunsearch/data
    expose:
      - "8383"
      - "8384"
    ports:
      - "8383:8383"
      - "8384:8384"
    # command:
    #   - "bin/xs-ctl.sh -b inet start"